name: Build and deploy ASP.Net Core app to Azure Web App - Workbuddy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'  # Adjust to your .NET Core version

      - name: Restore dependencies
        run: |
          cd dotnetapp/dotnetapp  # Adjust this path to your project directory
          dotnet restore
      - name: Build with dotnet
        run: |
          cd dotnetapp/dotnetapp  # Adjust this path to your project directory
          dotnet build --configuration Release
      - name: Publish artifact
        run: |
          cd dotnetapp/dotnetapp  # Adjust this path to your project directory
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Dev'
      url:  'workbuddybend.azurewebsites.net' # Replace with your Azure Web App URL
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'workbuddybend'  # Replace with your Azure Web App name
          slot-name: 'Dev'  # Replace with your Azure Web App deployment slot
          publish-profile: <publishData><publishProfile profileName="workbuddybend - Web Deploy" publishMethod="MSDeploy" publishUrl="workbuddybend.scm.azurewebsites.net:443" msdeploySite="workbuddybend" userName="$workbuddybend" userPWD="l6XJjxQfvjApvyhBi5gmDupN8tTodaDqN8Zjeo6PlmnZTvv7ssPf6Kf1qKhG" destinationAppUrl="https://workbuddybend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="workbuddybend - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-543.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="workbuddybend\$workbuddybend" userPWD="l6XJjxQfvjApvyhBi5gmDupN8tTodaDqN8Zjeo6PlmnZTvv7ssPf6Kf1qKhG" destinationAppUrl="https://workbuddybend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="workbuddybend - Zip Deploy" publishMethod="ZipDeploy" publishUrl="workbuddybend.scm.azurewebsites.net:443" userName="$workbuddybend" userPWD="l6XJjxQfvjApvyhBi5gmDupN8tTodaDqN8Zjeo6PlmnZTvv7ssPf6Kf1qKhG" destinationAppUrl="https://workbuddybend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: ${{ github.workspace }}/myapp  # Adjust this path if needed
